#!groovy

// Generated by IBM TransformationAdvisor
// Fri Mar 29 15:18:54 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}