#!groovy

// Generated by IBM TransformationAdvisor
// Fri Jan 11 09:49:40 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}